### PR TITLE
WIP: memory implementation revamp

### PR DESCRIPTION
**Pull request by Pwuts**
⚠️ This PR was moved to https://github.com/Significant-Gravitas/Auto-GPT/pull/4208

### CODE REVIEW

**Comment by katmai** [comment]
does the memory matter? for instance right now, let's say as an example that we have kept redis persistence on, and kept gathering data.
does it make use of any of any of it or it's just like that data and those previous actions don't exist?
the reason i ask is because i have done that. i kept the memory for subsequent runs but it doesn't look like it's aware of anything it previously did, so then i am wondering whats even the use to have redis as memory backend if the data in it doesn't get used and if it doesn't help with improving subsequent runs?

**Comment by Pwuts** [comment]
@katmai vector memory is currently disabled (since v0.3.0) because it wasn't being used effectively. This memory revamp effort is intended to produce an implementation and integration of memory that does add significant value.

**Comment by taksyon** [comment]
Will the MemoryItem class need to be incorporated into the chat_with_ai function in autogpt.llm.chat?

**Comment by Pwuts** [comment]
Moved to https://github.com/Significant-Gravitas/Auto-GPT/pull/4208

**Pull request closed without merging**
